### ISSUE TITLE
Compound Keys are not supported 

### ISSUE THREAD

**Issue by vidyah-sportsbet** [rkudryashov/graphql-java-federation#2]
Service B:
type TypeB {
  ... // attributes of TypeB

}

type TypeA @key(fields: "id { uid }") @extends {
    id: TypeAId ! @external
}

type TypeAId @extends {
    uid: ID! @external
}

Service A:

type TypeA @key(fields: "id { uid }") {
    id: TypeAId!
    name: String
}

type TypeAId @key(fields: "uid"){
    uid: ID!
    externalIds: [TypeAIdExternalId] //other fields ..
}

with above schema in the  , in a federated service -Service A.  where the TypeA and TypeAId GraphQL type are defined when the Federated Entity Resolver tries to get an Object of TypeA with TypeAId , it is not able to resolve the ID types , since the ID types are only expected to be simple keys and a Key field of type id { uid } is not supported 

In io.gqljf.federation.FederatedSchemaBuilder#getFederatedEntityId:
   final String idValue = (String) representation.get(idFieldName); (Line  154) 

The support needs to be added to lookup the Representation map for : id { uid } by lookup  first by key "id" and then in a second level map by "uid"

**Comment by rkudryashov** [comment]
Thanks for your interest in this library. Now I'm not sure I will maintain it.
