### ISSUE TITLE
Global Object Identification Specification - resolving Node interface 

### ISSUE THREAD

**Issue by saddis-r7** [rkudryashov/graphql-java-federation#3]
My GraphQL Service follows the Global Object Identification Specification. We provide an interface called Node. That interface must include exactly one field, called id that returns a non‐null ID.

How does the library take care of implementing services resolving the Node interface and every concrete type that implements Node?

**Comment by rkudryashov** [comment]
Thanks for your interest in this library. Now I'm not sure I will maintain it.
